Repository streamr-turing/streamr-fe, pull requests merged in 2023-02, with the labels that each got.

#29 Add styling to login page.
  src/Components/LoginPage/LoginPage.js
  src/Components/LoginPage/_LoginPage.scss
  src/tv.png
Labels: enhancement, front-end

#31 Build header component
  src/Components/App/App.js
  src/Components/Header/Header.js
  src/Components/Header/_Header.scss
  src/Components/MainLayout/MainLayout.js
  src/Components/MainLayout/_MainLayout.scss
Labels: enhancement, front-end

#35 Courtney/navbar/functionality
  src/Components/App/App.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/_NavBar.scss
  src/Components/NavBar/helper-functions.js
  src/Components/PageNotFound/PageNotFound.js
  src/Components/PageNotFound/_PageNotFound.scss
Labels: enhancement, front-end

#44 Courtney/feature/login page
  src/Components/App/App.js
  src/Components/LoginPage/LoginPage.js
  src/Components/LoginPage/_LoginPage.scss
  src/Providers/AllUsersContext.js
  src/Providers/AllUsersReducer.js
  src/Providers/AllUsersTypes.js
Labels: enhancement, front-end

#51 Courtney/fetch all users modal
  src/Components/App/App.js
  src/Components/LoginPage/LoginPage.js
  src/Components/RecModal/Friend/_Friend.scss
  src/Components/RecModal/RecModal.js
  src/Components/RecModal/_RecModal.scss
  src/GraphQL/Queries.js
  src/Providers/AllUsersContext.js
  src/Providers/AllUsersReducer.js
  src/Providers/AllUsersTypes.js
Labels: enhancement, front-end

#55 REFACTOR: Server Integration for currentUser
  src/Components/DetailsPage/DetailsPage.js
  src/Components/HomePage/HomePage.js
  src/Components/LoginPage/LoginPage.js
  src/Components/MainLayout/MainLayout.js
  src/Components/WatchListItem/WatchListItem.js
  src/Components/WatchlistPage/WatchlistPage.js
  src/GraphQL/Queries.js
  src/Providers/UserContext.js
  src/Providers/UserReducer.js
  src/Providers/UserTypes.js
Labels: enhancement, front-end

#57 REFACTOR: Update Client-Side Watchlist Logic to BE Data Structure
  src/Components/DetailsPage/DetailsPage.js
  src/Components/WatchListItem/WatchListItem.js
  src/Components/WatchlistPage/WatchlistPage.js
  src/GraphQL/Queries.js
  src/Providers/UserReducer.js
Labels: front-end

#61 Courtney/mutations modal
  src/Components/LoginPage/LoginPage.js
  src/Components/RecModal/RecModal.js
  src/GraphQL/Mutations.js
Labels: enhancement, front-end

#64 FEATURE: Full Watchlist Functionality
  src/Components/DetailsPage/DetailsPage.js
  src/Components/DetailsPage/_DetailsReccInterface.scss
  src/Components/HomePage/HomePage.js
  src/Components/RecommendeeCard/RecommendeeCard.js
  src/Components/SearchPage/SearchPage.js
  src/Components/SearchResultCard/SearchResultCard.js
  src/Components/TimelinePost/TimelinePost.js
  src/Components/WatchListItem/WatchListItem.js
  src/Components/WatchlistPage/WatchlistPage.js
  src/Hooks/useWatchlist.js
  src/Hooks/useWatchlistId.js
  src/Providers/UserReducer.js
Labels: enhancement, front-end

#77 REFACTOR: add dynamic genres and rating to search results
  src/Components/DetailsPage/DetailsTable.js
  src/Components/RecommendeeCard/RecommendeeCard.js
  src/Components/SearchPage/SearchPage.js
  src/Components/WatchListItem/WatchListItem.js
  src/GraphQL/Queries.js
Labels: front-end, MVP

#79 Courtney/cypress login
  .circleci/config.yml
  cypress/e2e/login_spec.cy.js
  cypress/fixtures/currentUser.json
  cypress/fixtures/login.json
  cypress/utilities/graphql-test-utils.js
Labels: front-end, Testing

#80 Add the no input tests.
  cypress/e2e/login_spec.cy.js
Labels: front-end, Testing

#82 Change Login Fixture file names.
  cypress/e2e/login_spec.cy.js
  cypress/fixtures/login-currentUser.json
  cypress/fixtures/login-users.json
Labels: front-end, Testing

#83 Make avatar and username dynamic and fix navbar scroll.
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/_NavBar.scss
Labels: bug, front-end

#86 Add tests and fixtures for watchlist_spec.
  cypress/e2e/watchlist_spec.cy.js
  cypress/fixtures/watchlist-currentUser-no-watchlist-items.json
  cypress/fixtures/watchlist-currentUser.json
  cypress/fixtures/watchlist-showDetails-30Rock.json
  cypress/fixtures/watchlist-shows-KingsOfQueens.json
  cypress/fixtures/watchlist-users.json
Labels: front-end, Testing

#92 Courtney/cypress modal
  cypress/e2e/recModal_spec.cy.js
  cypress/fixtures/recModal-createRecommendation-sean.json
  cypress/fixtures/recModal-currentUser.json
  cypress/fixtures/recModal-showDetails-30Rock.json
  cypress/fixtures/recModal-users-only-one.json
  cypress/fixtures/recModal-users.json
  src/Components/RecModal/RecModal.js
Labels: front-end, Testing

#93 Courtney/cypress error
  cypress/e2e/DetailsPage_spec.cy.js
  cypress/e2e/login_spec.cy.js
  cypress/e2e/recModal_spec.cy.js
  cypress/e2e/search_view_spec.cy.js
  cypress/e2e/watchlist_spec.cy.js
  src/Components/LoginPage/LoginPage.js
  src/Components/RecModal/RecModal.js
  src/Components/SearchPage/SearchPage.js
  src/GraphQL/Queries.js
Labels: front-end, Testing

#94 Change cypress timeout for Failed Modal Message to be 2000 instead of…
  cypress/e2e/recModal_spec.cy.js
Labels: bug, front-end

#95 TESTING: Watchlist Add/Remove Functionality
  cypress/e2e/AddRemoveWatchlist_spec.cy.js
  cypress/fixtures/DetailsPage-currentUser.json
  cypress/fixtures/createWatchlistItem.json
  cypress/fixtures/deleteWatchlistItem.json
  src/Components/RecommendeeCard/RecommendeeCard.js
  src/Components/SearchResultCard/SearchResultCard.js
  src/Components/TimelinePost/TimelinePost.js
  src/Components/WatchListItem/WatchListItem.js
Labels: front-end, Testing

#97 Add final styling to Navbar and overflow-y hidden to index.
  src/Components/NavBar/_NavBar.scss
  src/_index.scss
Labels: front-end

#98 FEATURE: Code Coverage/Final Cleanup
  .gitignore
  .nyc_output/out.json
  cypress.config.js
  cypress/e2e/AllSpecs_spec.cy.js
  cypress/plugins/index.js
  cypress/support/e2e.js
  cypress/support/index.js
  package-lock.json
  package.json
  public/index.html
  public/tv.png
  src/Components/DetailsPage/DetailsPage.js
  src/Components/LoginPage/LoginPage.js
  src/Components/RecommendeeCard/RecommendeeCard.js
  src/Components/SearchPage/SearchPage.js
  src/Components/SearchResultCard/SearchResultCard.js
  src/Components/WatchListItem/WatchListItem.js
  src/GraphQL/Queries.js
  src/Hooks/useWatchlist.js
  src/Providers/RecModalContext.js
  src/Providers/UserTypes.js
Labels: front-end, MVP, Testing
